version: 2
jobs:
  build:
    docker:
      - image: circleci/node:16.13.0
    steps:
      - checkout
      - run:
          name: set npm registry
          command: 'npm config set registry https://registry.npmjs.org/'
      - run:
          name: install-npm
          command: npm install
      - run:
          name: test
          command: MOCHA_FILE=~/junit/mocha/results.xml npm run ci-test
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
